# Generated by Django 6.0.6 on 2026-07-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_alumni',
            field=models.BooleanField(default=False, help_text="True once promoted to 'Alumni' — keeps records, hides from active directories."),
        ),
    ]
