# Generated by Django 6.0.6 on 2026-07-05 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time_label', models.CharField(blank=True, help_text="e.g. '9:00 AM - School Ground'", max_length=100)),
                ('audience', models.CharField(default='All Classes', max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('is_important', models.BooleanField(default=False)),
                ('all_school', models.BooleanField(default=True, verbose_name='All School')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classes', models.ManyToManyField(blank=True, help_text='Specific classes this announcement also targets.', related_name='announcements', to='academics.schoolclass')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
