# Generated by Django 6.0.6 on 2026-07-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('technical', 'Technical'), ('grammar', 'Grammar')], max_length=20)),
                ('level', models.CharField(help_text='e.g. F1MM, Form 1', max_length=30)),
                ('section', models.CharField(blank=True, help_text='Optional further split, e.g. A, B (leave blank if not needed).', max_length=10)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['stream', 'level', 'section'],
            },
        ),
    ]
