# Generated by Django 6.0.6 on 2026-07-05 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='level',
            field=models.CharField(choices=[('tvee_intermediate', 'TVEE Intermediate Level'), ('tvee_advanced', 'TVEE Advanced Level'), ('gce_ordinary', 'GCE Ordinary Level'), ('gce_advanced', 'GCE Advanced Level')], max_length=30),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='section',
            field=models.CharField(blank=True, help_text='The specific class, e.g. Form 1, F1MM, A.', max_length=30),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.schoolclass')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school_class', 'name')},
            },
        ),
    ]
